/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FlashcardsIndexImport } from './routes/flashcards/index'
import { Route as FlashcardsNewImport } from './routes/flashcards/new'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FlashcardsIndexRoute = FlashcardsIndexImport.update({
  path: '/flashcards/',
  getParentRoute: () => rootRoute,
} as any)

const FlashcardsNewRoute = FlashcardsNewImport.update({
  path: '/flashcards/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/flashcards/new': {
      id: '/flashcards/new'
      path: '/flashcards/new'
      fullPath: '/flashcards/new'
      preLoaderRoute: typeof FlashcardsNewImport
      parentRoute: typeof rootRoute
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  FlashcardsNewRoute,
  FlashcardsIndexRoute,
})

/* prettier-ignore-end */
